locals {
  public_hostname = "${var.hostname}.${var.zone_name}"
}

resource "local_file" "kusto_compose_override" {
  filename = "${path.module}/../../compose.override.yaml"
  content  = <<-YAML
    # Generated by infra/cloudflare-adx. Configure these values with Terraform variables.
    services:
      kusto:
        cpus: "${var.kusto_cpu_limit}"
        mem_limit: "${var.kusto_memory_limit}"
        memswap_limit: "${var.kusto_memory_limit}"
      kusto-defaultdb-cleaner:
        mem_limit: "1g"
        memswap_limit: "1g"
      kusto-readonly-gateway:
        mem_limit: "1g"
        memswap_limit: "1g"
      cloudflared:
        mem_limit: "1g"
        memswap_limit: "1g"
  YAML
}

resource "random_id" "tunnel_secret" {
  byte_length = 35
}

resource "cloudflare_zero_trust_tunnel_cloudflared" "adx" {
  account_id    = var.cloudflare_account_id
  config_src    = "cloudflare"
  name          = var.tunnel_name
  tunnel_secret = random_id.tunnel_secret.b64_std
}

resource "cloudflare_zero_trust_tunnel_cloudflared_config" "adx" {
  account_id = var.cloudflare_account_id
  tunnel_id  = cloudflare_zero_trust_tunnel_cloudflared.adx.id

  config = {
    ingress = [
      {
        hostname = local.public_hostname
        service  = var.local_service
      },
      {
        service = "http_status:404"
      }
    ]
  }
}

resource "cloudflare_zero_trust_access_service_token" "workshop" {
  account_id = var.cloudflare_account_id
  name       = var.student_service_token_name
  duration   = var.student_service_token_duration

  lifecycle {
    create_before_destroy = true
  }
}

resource "cloudflare_zero_trust_access_application" "adx" {
  account_id                = var.cloudflare_account_id
  app_launcher_visible      = false
  domain                    = local.public_hostname
  name                      = "Cyber Defense Workshop ADX Shared Credential"
  service_auth_401_redirect = false
  type                      = "self_hosted"

  policies = [
    {
      decision = "non_identity"
      include = [
        {
          service_token = {
            token_id = cloudflare_zero_trust_access_service_token.workshop.id
          }
        }
      ]
      name       = "Allow workshop shared service token"
      precedence = 1
    }
  ]
}

resource "cloudflare_dns_record" "adx" {
  count = var.manage_dns_with_api ? 1 : 0

  zone_id = var.cloudflare_zone_id
  name    = local.public_hostname
  type    = "CNAME"
  content = "${cloudflare_zero_trust_tunnel_cloudflared.adx.id}.cfargotunnel.com"
  ttl     = 1
  proxied = true
  comment = "Cyber Defense Workshop ADX Cloudflare Tunnel"
}