<#
.SYNOPSIS
Asserts the dashboard KQL and both dashboard JSON files describe the same 40 tiles.

.DESCRIPTION
There are three copies of the same dashboard content in this repository:

  dashboards/cyber-defense-workshop-dashboard.kql   the readable source, 40 `// Tile:` sections
  dashboards/cyber-defense-workshop-dashboard.json  schema 20, generated by New-WorkshopDashboard.ps1
  STUDENT-GUIDES/dashboard-CYBER-DEFEND-V4.json     schema 76, the file students import

They agree today. Nothing keeps them agreeing: the two JSON files hold 40 hand-
maintainable KQL queries each, and only the V4 file imports cleanly into a
current portal, so an edit made in the portal and exported over V4 would leave
the other two silently stale. A student would then be running a query the
instructor's answer key does not contain.

This compares tile titles across all three, and the query text of every tile
that carries one, normalising whitespace so formatting differences are not
reported as drift. The two schema versions store queries differently -- schema
20 inlines `tiles[].query`, schema 76 uses `tiles[].queryRef` into a top-level
`queries[]` -- so both shapes are resolved before comparison.

.EXAMPLE
.\scripts\Test-WorkshopDashboardParity.ps1

.NOTES
Exit code 0 when all three agree, 1 otherwise. No Azure, no Docker, no
generated data: this runs on a clean clone and in CI.
#>
#Requires -Version 7
[CmdletBinding()]
param(
    [string]$GeneratorPath = (Join-Path $PSScriptRoot 'New-WorkshopDashboard.ps1'),
    [string]$KqlPath = (Join-Path $PSScriptRoot '..' 'dashboards' 'cyber-defense-workshop-dashboard.kql'),
    [string]$GeneratedJsonPath = (Join-Path $PSScriptRoot '..' 'dashboards' 'cyber-defense-workshop-dashboard.json'),
    [string]$StudentJsonPath = (Join-Path $PSScriptRoot '..' 'STUDENT-GUIDES' 'dashboard-CYBER-DEFEND-V4.json'),
    [int]$ExpectedTileCount = 40
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

$script:Failures = 0

function Add-Failure {
    param([Parameter(Mandatory)][string]$Message)
    Write-Host ("  FAIL  {0}" -f $Message) -ForegroundColor Red
    $script:Failures++
}

function Get-NormalizedQuery {
    <#
        Compare meaning, not formatting. The portal reflows queries on export, so
        comparing raw text would report drift on every round trip and train
        people to ignore this check.
    #>
    param([string]$Text)

    if ([string]::IsNullOrWhiteSpace($Text)) { return '' }
    $lines = $Text -split '\r?\n' |
        ForEach-Object { ($_ -replace '\s+', ' ').Trim() } |
        Where-Object { $_ -and $_ -notmatch '^//' }
    return ($lines -join ' ').Trim()
}

function Get-KqlTileTitles {
    # Order matters and titles do not identify a tile: eight of the forty appear
    # twice, on different pages. So this returns a sequence, not a lookup.
    param([Parameter(Mandatory)][string]$Path)

    return @(
        [System.IO.File]::ReadAllLines((Resolve-Path -LiteralPath $Path)) |
            ForEach-Object { [regex]::Match($_, '^//\s*Tile:\s*(?<title>.+?)\s*$') } |
            Where-Object { $_.Success } |
            ForEach-Object { $_.Groups['title'].Value }
    )
}

function Get-JsonTiles {
    param([Parameter(Mandatory)][string]$Path)

    $document = Get-Content -LiteralPath $Path -Raw | ConvertFrom-Json

    # Schema 76 hoists query text into a top-level queries[] keyed by id, and the
    # tile points at it. Schema 20 inlines the query on the tile.
    $queriesById = @{}
    if ($document.PSObject.Properties['queries']) {
        foreach ($query in @($document.queries)) {
            $queriesById[[string]$query.id] = [string]$query.text
        }
    }

    $tiles = [System.Collections.Generic.List[pscustomobject]]::new()
    foreach ($tile in @($document.tiles)) {
        $text = ''
        if ($tile.PSObject.Properties['query'] -and $tile.query) {
            $text = [string]$tile.query
        }
        elseif ($tile.PSObject.Properties['queryRef'] -and $tile.queryRef) {
            foreach ($candidate in @('queryId', 'id', 'baseQueryId')) {
                if ($tile.queryRef.PSObject.Properties[$candidate] -and $tile.queryRef.$candidate) {
                    $id = [string]$tile.queryRef.$candidate
                    if ($queriesById.ContainsKey($id)) { $text = $queriesById[$id] }
                    break
                }
            }
        }

        $tiles.Add([pscustomobject]@{
                Id    = [string]$tile.id
                Title = [string]$tile.title
                Query = Get-NormalizedQuery $text
            })
    }

    return $tiles
}

foreach ($path in @($GeneratorPath, $KqlPath, $GeneratedJsonPath, $StudentJsonPath)) {
    if (-not (Test-Path -LiteralPath $path -PathType Leaf)) {
        throw "Dashboard artefact not found: $path"
    }
}

Write-Host ''
Write-Host 'Dashboard parity' -ForegroundColor Cyan
Write-Host ''

# ---- 1. the generated pair is current ------------------------------------------

# The strongest available check: regenerate and compare. It needs no knowledge of
# how the generator substitutes dashboard parameters, which is why comparing the
# .kql source text against the parameterised JSON was the wrong approach --
# `StartTime` in the source is `['_startTime']` in the output, and every tile
# would have reported drift.
$workingDirectory = Join-Path ([System.IO.Path]::GetTempPath()) ('cdw-dashboard-' + [guid]::NewGuid().ToString('N').Substring(0, 8))
New-Item -ItemType Directory -Path $workingDirectory -Force | Out-Null
try {
    $freshJson = Join-Path $workingDirectory 'dashboard.json'
    $freshKql = Join-Path $workingDirectory 'dashboard.kql'

    # Both outputs are redirected: the generator writes the .kql as well, so
    # leaving it at its default would rewrite a tracked file just to check it.
    & pwsh -NoProfile -File $GeneratorPath -OutputPath $freshJson -KqlPath $freshKql | Out-Null
    if ($LASTEXITCODE -ne 0) { throw 'New-WorkshopDashboard.ps1 failed to run.' }

    foreach ($pair in @(
            @{ Name = 'dashboard .json'; Committed = $GeneratedJsonPath; Fresh = $freshJson },
            @{ Name = 'dashboard .kql '; Committed = $KqlPath; Fresh = $freshKql }
        )) {
        if ((Get-FileHash -LiteralPath $pair.Committed -Algorithm SHA256).Hash -eq (Get-FileHash -LiteralPath $pair.Fresh -Algorithm SHA256).Hash) {
            Write-Host ('  PASS  {0} matches what the generator produces' -f $pair.Name) -ForegroundColor Green
        }
        else {
            Add-Failure ('{0} differs from what the generator produces' -f $pair.Name)
        }
    }
}
finally {
    Remove-Item -LiteralPath $workingDirectory -Recurse -Force -ErrorAction SilentlyContinue
}

# ---- 2. tile counts ------------------------------------------------------------

$kqlTitles = Get-KqlTileTitles -Path $KqlPath
$generated = Get-JsonTiles -Path $GeneratedJsonPath
$student = Get-JsonTiles -Path $StudentJsonPath

foreach ($set in @(
        @{ Name = 'kql (source)   '; Count = $kqlTitles.Count },
        @{ Name = 'json generated '; Count = $generated.Count },
        @{ Name = 'json student V4'; Count = $student.Count }
    )) {
    if ($set.Count -eq $ExpectedTileCount) {
        Write-Host ('  PASS  {0} has {1} tiles' -f $set.Name, $set.Count) -ForegroundColor Green
    }
    else {
        Add-Failure ('{0} has {1} tiles, expected {2}' -f $set.Name, $set.Count, $ExpectedTileCount)
    }
}

# ---- 3. the student handout still matches --------------------------------------

# Matched on tile id, not position. The two files hold the same forty tiles in
# different order -- 'Compromised User - Endpoint Activity' is tile 24 in the
# generated dashboard and tile 39 in the handout -- so comparing by index
# reported every tile from 24 onwards as drifted when nothing had changed. The
# ids correspond exactly because both derive from the same generator.
$generatedById = @{}
foreach ($tile in $generated) { $generatedById[$tile.Id] = $tile }

foreach ($tile in @($student | Where-Object { -not $generatedById.ContainsKey($_.Id) })) {
    Add-Failure ("student tile '{0}' has no matching id in the generated dashboard" -f $tile.Title)
}

if ($generated.Count -eq $student.Count) {
    $titleDrift = 0
    $queryDrift = 0

    foreach ($tile in $student) {
        if (-not $generatedById.ContainsKey($tile.Id)) { continue }
        $match = $generatedById[$tile.Id]

        if ($match.Title -ne $tile.Title) {
            $titleDrift++
            Add-Failure ("tile {0}: '{1}' in generated, '{2}' in student V4" -f $tile.Id, $match.Title, $tile.Title)
            continue
        }

        if ($match.Query -ne $tile.Query) {
            $queryDrift++
            Add-Failure ("'{0}': query differs between generated and student V4" -f $tile.Title)
            $a = $match.Query
            $b = $tile.Query
            Write-Host ('          generated : {0}' -f $a.Substring(0, [Math]::Min(100, $a.Length))) -ForegroundColor DarkGray
            Write-Host ('          student   : {0}' -f $b.Substring(0, [Math]::Min(100, $b.Length))) -ForegroundColor DarkGray
        }
    }

    if ($titleDrift -eq 0) { Write-Host ('  PASS  all {0} tile titles match' -f $generated.Count) -ForegroundColor Green }
    if ($queryDrift -eq 0) { Write-Host ('  PASS  all {0} tile queries match the student handout' -f $generated.Count) -ForegroundColor Green }
}

Write-Host ''
if ($script:Failures -gt 0) {
    Write-Host ("Dashboard parity FAILED: {0} problem(s)." -f $script:Failures) -ForegroundColor Red
    Write-Host ''
    Write-Host '  dashboards\*.json and dashboards\*.kql are build outputs. Regenerate them:'
    Write-Host '    .\scripts\New-WorkshopDashboard.ps1'
    Write-Host '  STUDENT-GUIDES\dashboard-CYBER-DEFEND-V4.json is what students import. If the'
    Write-Host '  generator changed, that handout must be re-exported so the answer key and the'
    Write-Host '  students are running the same query.'
    Write-Host ''
    exit 1
}

Write-Host 'The generated dashboards are current and the student handout matches them.' -ForegroundColor Green
Write-Host ''
exit 0
